# Generated by Django 3.2.7 on 2021-10-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210928_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('capacity', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('wifi', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('bathroom', models.BooleanField(default=False)),
                ('floors', models.IntegerField()),
            ],
        ),
    ]
