# Generated by Django 3.2.7 on 2021-10-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_houses'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='rooms',
            field=models.IntegerField(null=True),
        ),
    ]
