# Generated by Django 3.2.7 on 2021-10-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_houses_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='photo_preview',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
