# Generated by Django 3.2.7 on 2021-10-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211004_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='wifi',
            field=models.BooleanField(default=True),
        ),
    ]
