# Generated by Django 3.2.7 on 2021-10-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_houses_wifi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='bathroom',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='kitchen',
            field=models.BooleanField(default=True),
        ),
    ]
