# Generated by Django 3.2.7 on 2021-10-24 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_book_settlment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlment',
            name='date_booking',
        ),
        migrations.AddField(
            model_name='settlment',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.book'),
        ),
    ]
