# Generated by Django 3.2.7 on 2021-10-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211024_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії (ютуб)'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Відомі жінки', 'verbose_name_plural': 'Відомі жінки (ютуб)'},
        ),
    ]
