# Generated by Django 3.2.7 on 2021-10-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_houses_pets_allow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='central_heat',
            field=models.BooleanField(default=False),
        ),
    ]
