# Generated by Django 3.2.7 on 2021-10-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_houses_central_heat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-date_future_settlment'], 'verbose_name': 'Бронювання', 'verbose_name_plural': 'Бронювання'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ['-id'], 'verbose_name': 'Клієнт', 'verbose_name_plural': 'Клієнти'},
        ),
        migrations.AlterModelOptions(
            name='houses',
            options={'ordering': ['id'], 'verbose_name': 'Будинок', 'verbose_name_plural': 'Будинки'},
        ),
        migrations.AlterModelOptions(
            name='settlment',
            options={'ordering': ['-date_of_settlment'], 'verbose_name': 'Заселення', 'verbose_name_plural': 'Заселення'},
        ),
    ]
