# Generated by Django 3.2.7 on 2021-10-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20211024_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
